name: ASP.NET Core CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup Dotnet for use with actions
    - uses: actions/setup-dotnet@v1.0.0
      with:
        dotnet-version: '3.0.100'
    - name: Build with dotnet
      run: dotnet build --configuration Release
